### ISSUE TITLE
[QUESTION] Is it production ready?

### ISSUE THREAD

**Issue by Bobronium** [PrettyWood/future-typing#1]
Hi, @PrettyWood! I find this library very useful and would love to use it on my work projects. Would you strongly advise against it for now, or it seems stable enough to try at this point?

**Comment by Bobronium** [comment]
I guess, not yet. See #2 and #3. Possible that many other issues are still undiscovered.

**Comment by PrettyWood** [comment]
Hello @MrMrRobat! I'm glad you like it!
Indeed it's not production ready at all x) It's still purely experimental and has been tested only by me on small prototypes.
But I'm planning to work on it in the next few days and ll be more than happy to fix the spotted issues.
